const LARGE_SCREEN_SIZE = 769;
const MEDIUM_SCREEN_SIZE = 551;
const SMALL_SCREEN_SIZE = 550;
const MAX_CARDS_QTY = 12;
const MID_CARDS_QTY = 8;
const MIN_CARDS_QTY = 5;
const MAX_EXTRA_CARDS_QTY = 3;
const MID_EXTRA_CARDS_QTY = 2;
const MIN_EXTRA_CARDS_QTY = 2;

module.exports = {
   LARGE_SCREEN_SIZE,
   MEDIUM_SCREEN_SIZE,
   SMALL_SCREEN_SIZE,
   MAX_CARDS_QTY,
   MID_CARDS_QTY,
   MIN_CARDS_QTY,
   MAX_EXTRA_CARDS_QTY,
   MID_EXTRA_CARDS_QTY,
   MIN_EXTRA_CARDS_QTY
};
